#include	<string>
#include	<utility>
#include	<cereal/cereal.hpp>
#include	<cereal/types/polymorphic.hpp>
#include	"../../../imgui\\imgui.h"
#include	"../../../imgui\\imgui_internal.h"
#include	"NodeData.h"
//#include	"VoronoiNode.h"
#include	"../epion_string.h"
